"""Copy the fly page from docs/concept into a ClawStreet checkout.

    python scripts/publish_page.py /path/to/tradingclaw

docs/concept is the source. This writes three things in the checkout:
public/fly/ (scripts, models, textures), app/fly/fly.css (the page's rules,
scoped to .flypage), and components/fly/stage-markup.ts (the markup page.js draws into).
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / "docs" / "concept"
SCRIPTS = ["fly3d.js", "brain3d.js", "page.js"]
VENDOR = ["GLTFLoader.js", "RGBELoader.js"]
IMAGES = ["figure-fly.jpg", "massive-logo-white.svg", "massive-logo-black.svg"]
# Textures the scene does not load stay out of the site.
UNUSED = ["white_plaster_02_diff_1k.jpg", "wood_diff.jpg", "wood_rough.jpg"]
# Rules for markup that only the local page has.
DEAD = re.compile(r"\.site\b|\.avatar|\.pills|\.pill\b|\.id\b|\.ov-tl\b|\.ov-br\b|\.ov-rail|\.card\b|\.strip\b|\.callout|\.thought|"
                  r"\.follow\b|\.grid2|\.bars\b|\.bar\b|\.sim\b|\.kv\b|\.table3d|\.cap3d|\.step\b|\.tbl\b|\btable\b|\bth\b|\btd\b")
LIGHT = ':root[data-theme="light"]'

CSS_HEAD = """/* The /fly page. Every rule is scoped to .flypage. The page's color tokens use
   the same names as the site tokens with different value formats, so they
   must not reach the site header or footer. Generated by
   fly-brain/scripts/publish_page.py from docs/concept/index.html. */
"""
CSS_TAIL = """.flypage { margin: 0; }
.flypage .hero { width: 100%; margin: 0; }
.flypage .wrap { padding-block: 0 56px; }
.flypage .credits { margin: 0; }
.flypage .poster { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; transition: opacity .6s ease; }
.flypage .hero.live .poster { opacity: 0; pointer-events: none; }
"""
MARKUP_HEAD = """// The part of /fly that public/fly/page.js draws into. It is a string, not JSX,
// because page.js changes these nodes directly. React must not reconcile them.
// Generated by fly-brain/scripts/publish_page.py from docs/concept/index.html.
export const STAGE_MARKUP = `
"""
POSTER = ('<img class="poster" src="/fly/figure-fly.jpg" alt="A simulated fruit fly standing on a candlestick chart" '
          'width="1600" height="900" fetchpriority="high">\n    ')


def blocks(text: str) -> list[str]:
    out, depth, start = [], 0, 0
    for i, ch in enumerate(text):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                out.append(text[start:i + 1].strip())
                start = i + 1
    return out


def scope_selector(sel: str) -> str:
    sel = sel.strip()
    if sel in (":root", "body"):
        return ".flypage"
    if sel == LIGHT:
        return '[data-theme="light"] .flypage'
    if sel.startswith(LIGHT + " "):
        return '[data-theme="light"] .flypage ' + sel[len(LIGHT) + 1:]
    if sel == "html":
        return "html:has(.flypage)"
    return ".flypage " + sel


def scope_rule(rule: str) -> str | None:
    head, body = rule.split("{", 1)
    keep = [s for s in head.split(",") if not DEAD.search(s)]
    return ", ".join(scope_selector(s) for s in keep) + " {" + body if keep else None


def scoped_css(page: str) -> str:
    css = re.sub(r"/\*.*?\*/", "", page[page.index("<style>") + 7:page.index("</style>")], flags=re.S)
    out = []
    for block in blocks(css):
        if block.startswith("@media"):
            head, inner = block.split("{", 1)
            rules = [r for r in map(scope_rule, blocks(inner.rsplit("}", 1)[0])) if r]
            if rules:
                out.append(head.strip() + " {\n  " + "\n  ".join(rules) + "\n}")
        elif rule := scope_rule(block):
            out.append(rule)
    text = "\n".join(out)
    # The site sets the color scheme and loads the fonts.
    text = text.replace("color-scheme: dark;", "").replace("color-scheme: light;", "")
    text = text.replace('--sans: "Inter",', '--sans: var(--font-geist), "Inter",')
    text = text.replace('--mono: "JetBrains Mono",', '--mono: var(--font-jetbrains), "JetBrains Mono",')
    # The site styles bare header and footer elements, so the page uses classes.
    text = text.replace(".flypage header ", ".flypage .intro-head ").replace(".flypage footer", ".flypage .credits")
    return CSS_HEAD + text + "\n" + CSS_TAIL


def stage_markup(page: str) -> str:
    hero_at, intro_at = page.index('  <div class="hero">'), page.index('  <header style="padding-top:28px">')
    inside_at, how_at = page.index("  <section>"), page.index('  <section>\n    <div class="sec-head">\n      <h2 id="how">')
    hero = page[hero_at:intro_at].replace('<canvas id="fly3d"', POSTER + '<canvas id="fly3d"')
    intro = page[intro_at:inside_at].replace('<header style="padding-top:28px">', '<div class="intro-head" style="padding-top:28px">').replace("</header>", "</div>")
    body = hero.rstrip() + '\n  <div class="wrap">\n' + intro + page[inside_at:how_at].rstrip() + "\n  </div>\n"
    if "`" in body or "${" in body:
        raise SystemExit("the markup has a backtick or ${, which would break the template string")
    return MARKUP_HEAD + body + "`;\n"


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    site = Path(sys.argv[1]).resolve()
    if not (site / "app" / "layout.tsx").exists():
        raise SystemExit(f"{site} is not a ClawStreet checkout: app/layout.tsx is missing")
    public = site / "public" / "fly"
    (public / "vendor").mkdir(parents=True, exist_ok=True)
    for folder in ("model", "textures"):
        subprocess.run(["rsync", "-a", "--delete", *[f"--exclude={n}" for n in UNUSED], str(SRC / folder), str(public)], check=True)
    for name in SCRIPTS + IMAGES:
        shutil.copy2(SRC / name, public / name)
    for name in VENDOR:
        shutil.copy2(SRC / "vendor" / name, public / "vendor" / name)
    if not (public / "vendor" / "three.min.js").exists():
        print("public/fly/vendor/three.min.js is missing: add three.js r128, the site's CSP allows scripts from its own origin only")
    page = (SRC / "index.html").read_text()
    (site / "app" / "fly").mkdir(parents=True, exist_ok=True)
    (site / "components" / "fly").mkdir(parents=True, exist_ok=True)
    (site / "app" / "fly" / "fly.css").write_text(scoped_css(page))
    (site / "components" / "fly" / "stage-markup.ts").write_text(stage_markup(page))
    print(f"published to {site}")


if __name__ == "__main__":
    main()
